[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = {version = "1.24", features = ["full"] }

[dev-dependencies]
hyper = "0.14"
tower = "0.4"