name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build -t joeleav/hello-world .
    - run: docker run --name hello-world-test -d -p 3000:3000 joeleav/hello-world
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - run: docker push joeleav/hello-world
